config/routes.rb
Rails.application.routes.draw do
  get 'pages/show'
  # get 'categories/show'
  # get 'categories/index'
  resources :categories, only: [:index, :show]

  resources :products, only: :index
  resources :pages, only: :show
  resources :products, only: :show do
    collection do
      get 'search_results', to: ''
    end
  end

  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  post 'products/delete_from_cart/:id', to: 'products#delete_from_cart', as: 'delete_from_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  root to: 'products#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :Products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :Product
  belongs_to :Category
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :status
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :category_products, foreign_key: "Product_id"
  has_many :Categories, through: :category_products

  accepts_nested_attributes_for :category_products, allow_destroy: true

  validates :item, :description, :price, :stock, presence: true
  validates :stock, numericality: {only_integer: true}
  validates :stock, :percentDiscount, numericality: true

  has_one_attached :image
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.order(:name)
    @sort = Category.find(params[:id]).Products.sort_by { |p| p.item}
    @sorted = Kaminari.paginate_array(@sort).page(params[:page]).per(9)
  end

  def index
    @categories = Category.order(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :initialize_session
  before_action :load_cart

  def index
    @products = Product.order(:item).page(params[:page]).per(9)
    @categories = Category.order(:name)
  end

  def show
    @product = Product.find(params[:id])
    @categories = Category.order(:name)
  end

  def search_results
    @query = params[:query]
    @cat   = params[:category]

    if @cat == "ALL"
      @cat_name = "All Products"
      @results = Product.where('item LIKE ?', "%#{@query}%")
    elsif @cat == "SALE"
      @cat_name = "On Sale"
      @results = Product.where("percentDiscount > ?", 0.0)
    elsif @cat == "RU"
      @cat_name = "Recently Updated"
      @results = Product.where("updated_at > ?", DateTime.now.change(hour: 0))
    elsif
      @category = Category.find(@cat)
      @cat_name = @category.name
      @results = @category.Products.where('item LIKE ?', "%#{@query}%")
    end
  end

  def add_to_cart
    id = params[:id]
    count = 1
    if session[:cart][id]
      session[:cart][id]["item_count"] = session[:cart][id]["item_count"] + count
    else
      product = Product.find(id.to_i)
      session[:cart][id] = {"item_count" => count, "item" => product.item}
    end

    redirect_to root_path
  end

  def delete_from_cart
    id = params[:id]
    count = 1
    if session[:cart][id]["item_count"] > 1
      session[:cart][id]["item_count"] = session[:cart][id]["item_count"] - count
    else
      session[:cart].delete(id.to_s)
    end
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id]
    session[:cart].delete(id.to_s)
    redirect_to root_path
  end

  private

  def initialize_session
    session[:cart] ||= {}
  end

  def load_cart
    @cart = session[:cart]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>
  <% @categories.each do |category| %>
    <h4><strong><%= link_to category.name, category %></strong></h4>
  <% end%>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mt-5">
    <h1><strong><%= @category.name %></strong></h1>
  </div>
  <div class="row mt-4">
    <div class="col-3">
      <h2><u>Shop by Category</u></h2>
      <ul class="nav flex-column">
        <% @categories.each do |category| %>
        <li class="nav-item">
           <%= link_to category.name, category %>
        </li>
        <% end%>
      </ul>
    </div>
    <div class="col-9">
      <div class="container">
        <div class="row">
          <%= render partial: 'products/product', collection: @sorted, locals: { item_is_link: true }, :class => "col"%>
        </div>
        <div class="row justify-content-start mt-5">
          <%= paginate @sorted, window: 1 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InTurn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <nav class="navBarBorderBottom pokeColor navbar navbar-expand-md bg-dark navbar-dark">
       <a class="navbar-brand" href="/"><strong style="font-size: 26px">InTurn</strong> <span style="font-size: 14px">Curling Supplies<span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/pages/1">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/pages/2">Contact</a>
          </li>
        </ul>
      </div>
      <div>
          <%= form_with(url: search_results_products_path, method: "get", local: true) do %>
          <%= text_field_tag(:query) %>
          <%= select_tag :category,content_tag(:option,'All Products',:value=>"ALL")+content_tag(:option,'On Sale',:value=>"SALE")+content_tag(:option,'Recently Updated',:value=>"RU")+options_from_collection_for_select(Category.all, 'id', 'name') %>
          <%= submit_tag("Search") %>
          <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<div class="container-fluid">
  <div class="row mt-5">
    <h1 class="col text-center"><strong><%= @page.title%></strong></h1>
  </div>
  <div class="row justify-content-center mt-5">
    <h4 class="col-6 text-center"><strong><%= @page.description %></strong></h4>
  </div>
<div>

app/views/products/_product.html.erb
<div class="card m-2" style="width: 18rem;">
  <%# <img class="card-img-top" src="..." alt="Card image cap"> %>
  <div style="width: 16rem; background: #e3e3e3"></div>
  <%# <%= image_tag(product.image, alt: "Product", class: "card-img-top, img-responsive") %>
  <div class="d-flex  flex-column card-body">
    <% if item_is_link%>
      <h5 class="card-title"><%= link_to product.item, product %></h5>
    <% else %>
      <h5 class="card-title"><%= product.item %></h5>
    <% end %>
    <h5><strong>Price: </strong><%= number_to_currency product.price %></h5>

    <%if product.percentDiscount > 0.0 %>
     <h6><%= (product.percentDiscount * 100).round(0) %>% off (now just <%= number_to_currency (product.price - (product.price * product.percentDiscount)) %>)</h6>
    <% end %>

    <% if item_is_link%>
      <p class="card-text"><%= product.description.truncate(200) %></p>
    <% else %>
      <p class="card-text"><%= product.description %></p>
    <% end %>

    <% product.Categories.each do |category| %>
      <%= category.name %>
    <% end %>
      <button class="btn btn-success mt-auto"><%= link_to '+ cart', add_to_cart_path(product.id), method: :post, :class => "text-light" %></button>
 </div>
</div>

<%# desc[0..30].gsub(/\s\w+\s*$/,'...') %>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mt-5">
    <h1><strong>Welcome to InTurn</strong></h1>
  </div>

  <div class="row mt-4">
    <div class="col-3">


    <details>
      <summary>Shopping Cart</summary>
      <% if @cart.empty? %>
        <p>No items in cart.</p>
      <% else %>
        <ul>
          <% @cart.each do |product_id, product| %>
            <li>
              <%= product["item_count"] %> |
              <%= link_to '+', add_to_cart_path(product_id), method: :post %>
              <%= link_to '-', delete_from_cart_path(product_id), method: :post %>
              <%= link_to 'x', remove_from_cart_path(product_id), method: :delete %> |
              <%= product["item"] %>
            </li>
          <% end %>
         </ul>
       <% end %>
     </details>








      <h2><u>Shop by Category</u></h2>
      <ul class="nav flex-column">
        <% @categories.each do |category| %>
        <li class="nav-item">
           <%= link_to category.name, category %>
        </li>
        <% end%>
      </ul>
    </div>
    <div class="col-9">
      <div class="container">
        <div class="row">
          <%= render partial: 'products/product', collection: @products, locals: { item_is_link: true }, :class => "col"%>
        </div>
        <div class="row justify-content-start mt-5">
          <%= paginate @products, window: 1 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/search_results.html.erb
<div>
  <h2><%= @cat_name %><span><h4>- <%= @results.count %> results</h4></span></h2>
  <%= render partial: 'product', collection: @results, locals: {item_is_link: true} %>
</div>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-3">
      <h2>Shop by Category</h2>
      <ul class="nav flex-column">
        <% @categories.each do |category| %>
        <li class="nav-item">
           <%= link_to category.name, category %>
        </li>
        <% end%>
      </ul>
    </div>
    <div class="col-9">
      <div class="container">
        <div class="row">
           <div class="col-11"><%= render partial: 'product', object: @product, locals: { item_is_link: false } %></div>
        </div>
      </div>
    </div>
  </div>
</div>